trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
name: $(Year:yy).$(DayOfYear).$(Rev:rr)
steps:
- script: dotnet build --configuration $(build-configuration)
  displayName: 'dotnet build $(build-configuration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: '$(build-configuration)'
    nobuild: true
    versioningScheme: 'byBuildNumber'
    verbosityPack: 'Diagnostic'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget.Org'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-c $(build-configuration) -o $(build-dir) -r $(windows-os)'
- task: CopyFiles@1
  inputs:
    Contents: '**/$(build-dir)/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'