trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
name: $(Year:yy).$(DayOfYear).$(BuildID).$(Rev:rr)
steps:
- script: dotnet build --configuration $(build-configuration)
  displayName: 'dotnet build $(build-configuration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: '$(build-configuration)'
    packDirectory: '$(nuget-dir)'
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'nuget push'
    arguments: '$(nuget-dir)/DSM.GatewayEngine.$(Build.BuildNumber).nupkg -k $(nuget-api) -s $(nuget-url)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-c $(build-configuration) -o $(build-dir) -r $(windows-os)'
- task: CopyFiles@1
  inputs:
    Contents: '**/$(build-dir)/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'